[build]
  # Directory to publish (the public directory)
  publish = "public"
  # Build command (builds Go binary and prepares the public folder)
  command = "npm run build && ./cfd_simulator -config=default_config.json"
  
[build.environment]
  # Node.js version
  NODE_VERSION = "18.x"
  # Go version
  GO_VERSION = "1.20"

# Redirects and rewrite rules for the API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200